---
- name: Manage Docker instances via Ansible
  hosts: local
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Restart docker service
      command: service docker start
    - name: copying file to remote
      copy:
        src: ./{{item}}
        dest: /tmp/docker/
      loop: ['Dockerfile', 'flask-helloworld.py']
    - name: Build the image
      docker_image:
        build:
          path: /tmp/docker
          pull: yes
        name: helloworld
        source: build
    - name: Create Containers
      docker_container:
        name: helloworld-{{ item }}
        image: helloworld
        state: present
        ports:
         - "800{{item}}:5000"
      with_sequence: count=3
    - name: Start Containers
      docker_container:
        name: helloworld-{{ item }}
        image: helloworld
        state: started
        ports:
         - "800{{item}}:5000"
      with_sequence: count=3